install:
  name: caddy-internal
  location: /opt
  root: true
  volumes:
    - html
    - caddy.d
    - caddy_data
    - caddy_config
    - certs
  files:
    - compose.yml
    - Caddyfile
    - caddy.d
    - html
    - create-ca.sh
    - sign-domain.sh
  messages:
    - "You may need to docker pull caddy:latest manually"
    - "Run create-ca.sh to create the CA and for each domain, run sign-domain.sh to sign the domain"
